import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ticket App",
  description: "Generated by Ritabrata ",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* now the navbar will be displayed on every page */}
        <div className="flex flex-col h-screen max-h-screen">
          <Nav/>
          <div className="flex-grow overflow-y-auto bg-page text-default-text">
            {children}
            <Toaster/>
          </div>
          
        </div>
        
      </body>
    </html>
  );
}
